# 定议变量
variables:
  DOCKER_REGITSTOR: "docker.hnjing.com:5000"
  SERVER_NAME: "ability/gateway"
# 建构前执行的脚本
before_script:
  - echo gittag:$CI_BUILD_TAG
build:
  only: #指定只有打了标才执行
    - tags
  script:
  # build时传入SERVICE_VERSION参数
    - docker build --build-arg SERVICE_VERSION=$CI_BUILD_TAG -t $DOCKER_REGITSTOR/$SERVER_NAME:$CI_BUILD_TAG .
    - docker push $DOCKER_REGITSTOR/$SERVER_NAME:$CI_BUILD_TAG
    # 镜像上传后删除本地镜像，避免冗余
    - docker rmi $DOCKER_REGITSTOR/$SERVER_NAME:$CI_BUILD_TAG
 
  tags: 
  # 指定使用jwrunner来建构
    - jw-runner_1